### ISSUE TITLE
Kali Linux Wireless Adapter

### ISSUE THREAD

**Issue by will09122000** [teodorcucu/m1-kali-linux-umt#1]
I got it working but I kind of need a wireless adapter to work in the VM for my coursework. Is this possible?

**Comment by teodorgross** [comment]
In general, it must run without problems or any manual installation of network drivers. 

Can you show me your configuration from the "Network" Tab in UTM?

**Comment by will09122000** [comment]
Network tab:
![image](https://user-images.githubusercontent.com/41238606/102506069-a6967c80-407a-11eb-93f4-b0331b5b5702.png)
Emulated Network Card options:
![image](https://user-images.githubusercontent.com/41238606/102506121-b44c0200-407a-11eb-8453-3bea546e7640.png)

**Comment by teodorgross** [comment]
Sorry i had to be offline for a while. 

I think this update is outdatet since it works trough parallels ;)
